int    number_of_parameters_by_spots = 23 ;
int    number_of_base_parameters = 28 ;
final int BLADE_BASE_OFFSET = 3 ;  // index DMX du premier canal blade (A1 MSB)
boolean is_cursor_visible = false;
int    used_screen;
int    screen_number ;
int    win_width  = 800;
int    win_height = 600;
int    bg_color ;
int    blend_mode ;
String blend_mode_string ;
int    number_of_spots ;
int    artnet_start_universe ;
int    artnet_start_address = 0;
byte[] dmx_data ;
int    end_universe ;
int    end_address ;
int    n_used_universes_minus_one ;
String iface_address ;
PFont  f ;
PFont[] font_cache = {};
String[] available_fonts = {};
int    selected_font_idx  = 0;
