int    number_of_parameters_by_spots = 20 ;
int    number_of_base_parameters = 28 ;
boolean is_cursor_visible = false;
int    used_screen;
int    screen_number ;
int    win_width  = 800;
int    win_height = 600;
int    bg_color ;
int    blend_mode ;
String blend_mode_string ;
int    number_of_spots ;
int    artnet_start_universe ;
int    artnet_start_address = 0;
int    spot_color ;
int    spot_alpha ;
int    spot_stroke ;
int    spot_stroke_alpha ;
int    spot_stroke_color ;
float  spot_size_pan ;
float  spot_size_tilt ;
float  spot_rotation ;
float  spot_position_pan ;
float  spot_position_tilt ;
int    spot_mode ;
byte[] dmx_data ;
int    end_universe ;
int    end_address ;
int    n_used_universes_minus_one ;
String iface_address ;
PFont  f ;
